spring.application.name=springjwt
logging.level.root=ERROR
logging.level.org.springframework.boot.tomcat=INFO
logging.level.org.springframework.boot.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
jwt.secret=7147745e0de196b83236fad1a281958a96882930c6ececd68c02c862fe5b0d81
frontend.url=http://localhost:4200